* Numpy consists of multidimensional array objects and collection of routines or function  for processing the array.

In [1]:
#Statement to import the numpylibrary
import numpy as np

In [2]:
#one dimensional array
prime_array=np.array([1,2,3,4,5]) #limitation :  numpy array have same type item of data like : only int or only float only or only str

In [3]:
print(prime_array)

[1 2 3 4 5]


In [4]:
type(prime_array)

numpy.ndarray

In [5]:
prime_array.shape

(5,)

In [6]:
# 2D array
two_dimensional = np.array([[3,4,7],[4,6,9]])

In [7]:
two_dimensional

array([[3, 4, 7],
       [4, 6, 9]])

In [8]:
two_dimensional.shape

(2, 3)

In [9]:
#3d array
third_Arry = np.array([[[3,5,5],[9,6,8]],
                       [[8,9,6],[8,9,9]]])

In [10]:
third_Arry.shape

(2, 2, 3)

In [11]:
print(third_Arry)

[[[3 5 5]
  [9 6 8]]

 [[8 9 6]
  [8 9 9]]]


In [12]:
a = np.array([1,2,3,4,5])

In [13]:
a

array([1, 2, 3, 4, 5])

In [14]:
print(a)

[1 2 3 4 5]


In [15]:
r_a = np.random.random((4,3)) #1darray

In [16]:
r_a

array([[0.60005002, 0.12122719, 0.07537179],
       [0.18516089, 0.06265007, 0.19689876],
       [0.89774081, 0.97628368, 0.95534587],
       [0.44721281, 0.95315478, 0.01707195]])

In [17]:
r_a = np.random.randint(5,50,(4,3)) #2d array

In [18]:
r_a

array([[41, 42, 29],
       [27,  7, 12],
       [13, 38, 40],
       [42, 14, 40]])

In [19]:
r_a = np.random.randint(5,50,(2,4,3)) #3darray

In [20]:
r_a

array([[[40, 17, 32],
        [20, 25,  5],
        [21, 33, 40],
        [47, 15, 48]],

       [[48, 26, 49],
        [36, 18,  7],
        [37,  5,  8],
        [36, 35, 35]]])

In [21]:
# Numpy array attributes

In [22]:
# ndarray.shape
r_a.shape

(2, 4, 3)

In [23]:
# ndarray.ndim  (number of dimemsions)

r_a.ndim

3

In [24]:
# ndarray.size  (return number of elemnets that presents inside of your array)

r_a.size

24

In [25]:
#ndarray.dtype (datatype of elements )

r_a.dtype

dtype('int32')

In [26]:
# Functinality of numpy of array

In [27]:
l = [1,2,3,4]

In [28]:
l+5  # not possible in list 

TypeError: can only concatenate list (not "int") to list

In [ ]:
r_a+10

In [ ]:
r_a*10      #elementwise opertaion in numpy

In [ ]:
r_a

In [ ]:
r_a[0,2,1]

In [ ]:
r_a[1,0:2,1:]

In [ ]:
r_a[1:2,0:2,1:]

In [ ]:
r_a

In [ ]:
r_a[0,1:,1]

In [ ]:
r_a[0:1,1:,1:2]

In [ ]:
import numpy as np

# step 4: Numpy functions or method

In [30]:
 a2 = np.random.randint(10,100,(4,3))

In [31]:
a2

array([[87, 12, 90],
       [91, 34, 36],
       [96, 24, 76],
       [81, 21, 87]])

In [32]:
# Transpose

np.transpose(a2)

array([[87, 91, 96, 81],
       [12, 34, 24, 21],
       [90, 36, 76, 87]])

In [33]:
a2t = np.transpose(a2)

In [34]:
a2t

array([[87, 91, 96, 81],
       [12, 34, 24, 21],
       [90, 36, 76, 87]])

In [35]:
# Reshape

a2.shape

(4, 3)

In [36]:
a2.size  #row*column = total number of element

12

In [37]:
np.reshape(a2,(3,4))

array([[87, 12, 90, 91],
       [34, 36, 96, 24],
       [76, 81, 21, 87]])

In [38]:
np.reshape(a2,(2,3,2))        #number of elements remain same

array([[[87, 12],
        [90, 91],
        [34, 36]],

       [[96, 24],
        [76, 81],
        [21, 87]]])

In [39]:
#Resize

np.resize(a2,(5,6))

array([[87, 12, 90, 91, 34, 36],
       [96, 24, 76, 81, 21, 87],
       [87, 12, 90, 91, 34, 36],
       [96, 24, 76, 81, 21, 87],
       [87, 12, 90, 91, 34, 36]])

In [40]:
# Flatten

a2

array([[87, 12, 90],
       [91, 34, 36],
       [96, 24, 76],
       [81, 21, 87]])

In [47]:
a3 = np.reshape(a2,(2,3,2))        
a3

array([[[87, 12],
        [90, 91],
        [34, 36]],

       [[96, 24],
        [76, 81],
        [21, 87]]])

In [46]:
a3.flatten() #converting any type matrix in 1d array.

array([87, 12, 90, 91, 34, 36, 96, 24, 76, 81, 21, 87])

In [48]:
a3

array([[[87, 12],
        [90, 91],
        [34, 36]],

       [[96, 24],
        [76, 81],
        [21, 87]]])

In [ ]:
l1 =[1,2,3,4]

# cloning and coping

In [ ]:
l2 = l1 #cloning

In [ ]:
l2

In [ ]:
l2.pop()

In [ ]:
l1

In [ ]:
l3 = l1.copy()  #copying

In [ ]:
l3

In [ ]:
l3.pop()

In [ ]:
l3

In [ ]:
l1

In [ ]:
 an = np.full((4,3),30)

In [ ]:
an